// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIGSLeesWR7rRcul-i2VwyBN4ZOi7BOMk',
    appId: '1:125145176612:web:3f3e02da85b0441c30d6b1',
    messagingSenderId: '125145176612',
    projectId: 'parkinson-detection-app',
    authDomain: 'parkinson-detection-app.firebaseapp.com',
    storageBucket: 'parkinson-detection-app.appspot.com',
    measurementId: 'G-C0VBGCZ5HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsPdr99c8asgpRwWsjmyMWWWeqemjgn9I',
    appId: '1:125145176612:android:506d7a205f8da91230d6b1',
    messagingSenderId: '125145176612',
    projectId: 'parkinson-detection-app',
    storageBucket: 'parkinson-detection-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3t3rwUwfeISZHKFjFS9-dSHRYPOEtGZk',
    appId: '1:125145176612:ios:738594ee06642a2230d6b1',
    messagingSenderId: '125145176612',
    projectId: 'parkinson-detection-app',
    storageBucket: 'parkinson-detection-app.appspot.com',
    iosClientId: '125145176612-f3f5an7gkr6g81fhle47mo4a75or1nhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkinsonDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3t3rwUwfeISZHKFjFS9-dSHRYPOEtGZk',
    appId: '1:125145176612:ios:738594ee06642a2230d6b1',
    messagingSenderId: '125145176612',
    projectId: 'parkinson-detection-app',
    storageBucket: 'parkinson-detection-app.appspot.com',
    iosClientId: '125145176612-f3f5an7gkr6g81fhle47mo4a75or1nhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkinsonDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIGSLeesWR7rRcul-i2VwyBN4ZOi7BOMk',
    appId: '1:125145176612:web:96f028f3d803770a30d6b1',
    messagingSenderId: '125145176612',
    projectId: 'parkinson-detection-app',
    authDomain: 'parkinson-detection-app.firebaseapp.com',
    storageBucket: 'parkinson-detection-app.appspot.com',
    measurementId: 'G-LG3T0M3LYV',
  );

}